openapi: 3.0.0
info:
  title: Chat API
  version: 1.0.0
  description: API for finding documents and chatting

paths:
  /find:
    get:
      summary: Find documents
      operationId: findDocs
      parameters:
        - name: topic
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: string

  /chat:
    post:
      summary: Chat endpoint
      operationId: chatEndpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
        - history
      properties:
        message:
          type: string
        history:
          type: array
          items:
            type: string

    Error:
      type: object
      properties:
        detail:
          type: string